# Generated by Django 4.2.2 on 2023-06-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Ques", models.TextField()),
                ("Ans", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="person",
            old_name="first_name",
            new_name="First_name",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="last_name",
            new_name="Last_name",
        ),
    ]
