# Generated by Django 4.2.2 on 2023-06-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0003_reviews"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="MyReview",
        ),
    ]
