# Generated by Django 4.2.2 on 2023-06-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0004_rename_reviews_myreview"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyReview",
            new_name="Review",
        ),
    ]
