# Generated by Django 4.2.2 on 2023-06-26 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0005_rename_myreview_review"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Review",
            new_name="Reviews",
        ),
    ]
