# Generated by Django 4.2.2 on 2023-06-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0006_rename_review_reviews"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviews",
            new_name="Review",
        ),
    ]
