# Generated by Django 4.2.2 on 2023-06-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0008_myreview_delete_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="Changepassword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=10000)),
                ("Message", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="HelpandSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=10000)),
                ("Message", models.TextField()),
            ],
        ),
    ]
