# Generated by Django 4.2.2 on 2023-06-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0009_changepassword_helpandsupport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10000)),
                ("Email", models.EmailField(max_length=254)),
                ("Subject", models.CharField(max_length=10000)),
                ("Message", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Changepassword",
        ),
    ]
