# Generated by Django 4.2.2 on 2023-06-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0010_contactus_delete_changepassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10000)),
                ("Email", models.EmailField(max_length=254)),
                ("Password", models.CharField(max_length=10000)),
            ],
        ),
    ]
