# Generated by Django 4.2.2 on 2023-06-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0011_register"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="register",
            new_name="user_register",
        ),
    ]
