# Generated by Django 4.2.2 on 2023-06-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0012_rename_register_user_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10000)),
                ("Description", models.CharField(max_length=10000)),
                ("Image", models.ImageField(upload_to="")),
                ("Writter", models.CharField(max_length=10000)),
            ],
        ),
    ]
