# Generated by Django 4.2.2 on 2023-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0013_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="Description",
            field=models.TextField(),
        ),
    ]
