# Generated by Django 4.2.2 on 2023-06-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0014_alter_blog_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="EditProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=10000)),
                ("Age", models.CharField(max_length=10000)),
                ("Gender", models.CharField(max_length=10000)),
                ("DOB", models.CharField(max_length=10000)),
                ("PhoneNo", models.CharField(max_length=10000)),
            ],
        ),
    ]
