# Generated by Django 4.2.2 on 2023-06-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0015_editprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
