# Generated by Django 4.2.2 on 2023-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0016_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="Age",
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_register",
            name="DOB",
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_register",
            name="Gender",
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_register",
            name="PhoneNo",
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
