# Generated by Django 4.2.2 on 2023-06-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0017_user_register_age_user_register_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="Age",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="user_register",
            name="DOB",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="user_register",
            name="Gender",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="user_register",
            name="PhoneNo",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
