# Generated by Django 4.2.2 on 2023-06-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0018_alter_user_register_age_alter_user_register_dob_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EditProfile",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
