# Generated by Django 4.2.2 on 2023-06-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0019_delete_editprofile_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="Name",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="user_register",
            name="Password",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
