# Generated by Django 4.2.2 on 2023-06-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0020_alter_user_register_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_register",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
