# Generated by Django 4.2.2 on 2023-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0023_category_alter_video_title_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("video", models.FileField(upload_to="")),
            ],
        ),
    ]
