# Generated by Django 4.2.2 on 2023-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0024_initiative"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="initiative",
            name="video",
        ),
        migrations.AddField(
            model_name="initiative",
            name="Description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="initiative",
            name="Image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
