# Generated by Django 4.2.3 on 2023-07-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0025_remove_initiative_video_initiative_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_register",
            name="Profie",
            field=models.ImageField(blank=True, null=True, upload_to="imgs"),
        ),
    ]
