# Generated by Django 4.2.3 on 2023-07-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AIapp", "0026_user_register_profie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_register",
            old_name="Profie",
            new_name="Profile",
        ),
    ]
